### ISSUE TITLE
Error de captura de variable Capacidad

### ISSUE THREAD

**Issue by bryantmencia014** [Djsiclait/AlquiCarro#1]
public static void RegistrarCarro(){
     // Capturar la informacion del usuario
    Scanner teclado= new Scanner(System.in);
        
    System.out.println("Marca: ");
    String Marca= teclado.nextLine();    // Capturando la informacion del usuario.
    System.out.println("Modelo: ");
    String Modelo= teclado.nextLine();   // Capturando la informacion del usuario.
    System.out.println("Ano: ");
    int Ano = teclado.nextInt();         // Capturando la informacion del usuario.
    System.out.println("Precio: ");
    int Precio = teclado.nextInt();      // Capturando la informacion del usuario.
    System.out.println("Deposito: ");
   int Deposito = teclado.nextInt();    // Capturando la informacion del usuario.
    System.out.println("IDCarro: ");
    int IDCarro = teclado.nextInt();      // Capturando la informacion del usuario.
    System.out.println("Capacidad: ");   // TODO: narreglar error capturar capacidad.
    String Capacidad = teclado.nextLine();
    
    listaCarro.add(new Carro(Marca,Modelo,Ano,Precio,Deposito,Capacidad,IDCarro));
    
    System.out.println(" \t 'Informacion Capturada' ");
    
   }

**Comment by Djsiclait** [comment]
La rama se llama Aggregar/funcion/RegistrarCarros

**Comment by Djsiclait** [comment]
Limpie el codigo un poco

**Comment by Djsiclait** [comment]
Arregle el error de captura de la variable

en java nextline() es un poco sensitivo, si se llama después de nextInt() o otra cosas es posible que captura residuos de la primera funcion. 

De aqui en adelnte, siempre poner todos los nextLine() antes de cualquier otro tipo de captura de entrada @bryantmencia014 @AlfredoGru
